import serverPack from "../content/server/forest-of-patience-climbing-stairs.json";

/**
 * Server-side view of a quest pack: everything except hidden submit tests,
 * which exist only in the runner service. Generated by
 * scripts/build_pack_projections.py. Never import this from client code,
 * because it carries solutions and hint text.
 */
export type QuestPack = {
  schemaVersion: string;
  id: string;
  slug: string;
  title: string;
  concepts: string[];
  quests: QuestChallenge[];
  boss: QuestChallenge;
  review?: { enabled: boolean; defaultSchedule: number[] };
  rewards?: { xp?: { solutionAssistedMultiplier?: number; hintAssistedMultiplier?: number } };
};

export type QuestChallenge = {
  id: string;
  title: string;
  hints?: Array<{ id: string; text: string; cost: string }>;
  solution: { code: string };
  unlock?: { requiresQuestIds?: string[] };
  rewards?: { xp?: number; shards?: number };
};

const PACKS: Record<string, QuestPack> = { [serverPack.slug]: serverPack };

export function listPackSlugs() {
  return Object.keys(PACKS);
}

export function loadQuestPack(slug: string): QuestPack {
  const pack = PACKS[slug];
  if (!pack) throw new Error(`Unknown quest pack: ${slug}`);
  return pack;
}

export function findChallenge(pack: QuestPack, challengeId: string): QuestChallenge {
  const challenge = [...pack.quests, pack.boss].find((item) => item.id === challengeId);
  if (!challenge) throw new Error(`Challenge not found: ${challengeId}`);
  return challenge;
}

export function findChallengeById(challengeId: string): { pack: QuestPack; challenge: QuestChallenge } | null {
  for (const pack of Object.values(PACKS)) {
    const challenge = [...pack.quests, pack.boss].find((item) => item.id === challengeId);
    if (challenge) return { pack, challenge };
  }
  return null;
}

/** Hint text and solutions the player has already opened, keyed by challenge id. */
export function revealedContent(progress: { hintsOpened: Record<string, number>; solutionOpened: Record<string, boolean> }) {
  const hints: Record<string, string[]> = {};
  const solutions: Record<string, string> = {};
  for (const pack of Object.values(PACKS)) {
    for (const challenge of [...pack.quests, pack.boss]) {
      const opened = progress.hintsOpened[challenge.id] ?? 0;
      if (opened > 0) hints[challenge.id] = (challenge.hints ?? []).slice(0, opened).map((hint) => hint.text);
      if (progress.solutionOpened[challenge.id]) solutions[challenge.id] = challenge.solution.code;
    }
  }
  return { hints, solutions };
}
